In [1]:
import os

os.getcwd()
os.chdir("../../")
os.getcwd()

'/data01/dl23vitcas/dl_project'

In [2]:
import sys
import argparse
import os

sys.argv = ["view", "--config", "config/single_task_object_detection.yaml"]

parser = argparse.ArgumentParser()
parser.add_argument("--config", type=str, required=True, help="Path to the config file")
args = parser.parse_args()

print(args.config)

config/single_task_object_detection.yaml


In [3]:
import torch
import torch.nn.functional as F
import torch.nn as nn

In [4]:
W = torch.arange(12, dtype=torch.float32).reshape(4, 3)
b = torch.arange(4, dtype=torch.float32)
print(W)
print(b)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
tensor([0., 1., 2., 3.])


# SVD


In [ ]:
U, S, V = torch.svd(W)

In [ ]:
print(U)
print(S)
print(torch.diag(S))
print(V)

In [ ]:
U @ torch.diag(S) @ V.t()  # deve essere un'approssimazione di W

# Truncated SVD


In [5]:
U, S, V = torch.svd(W)

In [6]:
t = 2
St = S[:t]
St_diag = torch.diag(St)

In [7]:
print(St)
print(St_diag)

tensor([22.4467,  1.4641])
tensor([[22.4467,  0.0000],
        [ 0.0000,  1.4641]])


In [8]:
# pad: left, right, up, down
# aggiunge un numero di colonne e righe di padding specificato  in questo caso solo una a destra e una sotto
St_diag = F.pad(input=St_diag, pad=(0, 1, 0, 1), mode="constant", value=0)
print(St_diag)

tensor([[22.4467,  0.0000,  0.0000],
        [ 0.0000,  1.4641,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])


In [9]:
U @ St_diag @ V.t()  # deve essere un'approssimazione di W

tensor([[1.7881e-07, 1.0000e+00, 2.0000e+00],
        [3.0000e+00, 4.0000e+00, 5.0000e+00],
        [6.0000e+00, 7.0000e+00, 8.0000e+00],
        [9.0000e+00, 1.0000e+01, 1.1000e+01]])

To compress a network, the single fully connected layer corresponding to W is replaced by two fully connected layers, without a non-linearity between them. The first of these layers uses the weight matrix ΣtV T (and no biases) and the second uses U (with the original bi- ases associated with W ). This simple compression method gives good speedups when the number of RoIs is large.


# change weights matrix to FC layers


In [10]:
W = torch.arange(12, dtype=torch.float32).reshape(4, 3)
b = torch.arange(4, dtype=torch.float32)
fc = torch.nn.Linear(3, 4, bias=True)
fc.weight = torch.nn.Parameter(W)
fc.bias = torch.nn.Parameter(b)
print(fc.weight)
print(fc.bias)

Parameter containing:
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], requires_grad=True)
Parameter containing:
tensor([0., 1., 2., 3.], requires_grad=True)


In [11]:
U, S, V = torch.svd(fc.weight)
t = 2
St = S[:t]
St_diag = torch.diag(St)
St_diag = F.pad(input=St_diag, pad=(0, 1, 0, 1), mode="constant", value=0)

In [12]:
desired_weights = St_diag @ V.t()
input_size = desired_weights.size(1)
output_size = desired_weights.size(0)
first_fc_layer = nn.Linear(input_size, output_size, bias=False)

with torch.no_grad():
    first_fc_layer.weight = nn.Parameter(desired_weights)

print("Pesi:", first_fc_layer.weight)
print("Bias:", first_fc_layer.bias)

Pesi: Parameter containing:
tensor([[-11.1689, -12.8838, -14.5986],
        [ -1.1205,  -0.0913,   0.9379],
        [  0.0000,   0.0000,   0.0000]], requires_grad=True)
Bias: None


In [13]:
desired_weights = U
desired_bias = fc.bias

input_size = desired_weights.size(1)
output_size = desired_weights.size(0)
fc_layer = nn.Linear(input_size, output_size)

with torch.no_grad():
    fc_layer.weight = nn.Parameter(desired_weights)
    fc_layer.bias = nn.Parameter(desired_bias)

# Stampa pesi e bias per verificare
print("Pesi:", fc_layer.weight)
print("Bias:", fc_layer.bias)

Pesi: Parameter containing:
tensor([[-0.0835,  0.8325,  0.5319],
        [-0.3137,  0.4490, -0.8066],
        [-0.5438,  0.0656,  0.0176],
        [-0.7739, -0.3179,  0.2571]], requires_grad=True)
Bias: Parameter containing:
tensor([0., 1., 2., 3.], requires_grad=True)


In [14]:
import torch
import torch.nn as nn
import torch.nn.functional as F


def truncated_svd_decomposition(layer, t):
    """
    Applies truncated SVD decomposition on the given linear layer.

    Args:
    - layer (nn.Linear): The linear layer to be decomposed.
    - t (int): Number of singular values to keep.

    Returns:
    - nn.Sequential: A sequential model with two linear layers representing the truncated SVD.
    """
    # Perform SVD on the weight matrix
    W = layer.weight.data
    U, S, V = torch.svd(W)

    # Keep only the top t singular values
    U_t = U[:, :t]
    S_t = S[:t]
    V_t = V[:, :t]

    # Create the two new linear layers
    first_layer = nn.Linear(V_t.shape[0], t, bias=False)
    second_layer = nn.Linear(t, U_t.shape[0], bias=True)

    # Initialize the weights of the new layers
    first_layer.weight.data = (S_t.unsqueeze(1) * V_t.t()).t()
    second_layer.weight.data = U_t.t()

    # Set the bias of the second layer to be the same as the original layer
    second_layer.bias.data = layer.bias.data.clone()

    # Return a sequential model of the two layers
    return nn.Sequential(first_layer, second_layer)


# Example usage
original_layer = nn.Linear(4096, 4096)
compressed_layer = truncated_svd_decomposition(original_layer, t=256)

In [15]:
original_layer.weight[:20, :20]

tensor([[ 1.5500e-02, -1.1317e-02, -5.1503e-03, -5.1536e-03,  6.5579e-03,
          1.0705e-02,  1.5183e-02,  3.4646e-03, -1.6757e-03, -1.0893e-02,
         -6.0354e-03,  6.3926e-03, -1.5673e-03,  8.1092e-03, -1.1599e-02,
          1.4426e-02,  2.5974e-03,  1.8155e-03, -1.3896e-02,  1.3803e-02],
        [ 1.3938e-02, -1.3989e-02, -2.5626e-03,  1.4210e-03, -1.1655e-02,
         -1.3734e-02, -1.5059e-04, -4.9211e-04, -6.2377e-03, -7.3574e-03,
         -2.1719e-03,  1.1371e-02,  2.5853e-03, -1.3306e-02,  1.0336e-02,
          1.1554e-02,  5.7183e-03, -1.8824e-04,  7.8216e-03,  8.1912e-03],
        [ 3.8656e-03,  1.3437e-02, -9.2378e-03,  6.0396e-03, -3.7877e-03,
          7.5782e-03, -5.8893e-03, -9.6058e-03,  1.5215e-02,  2.3395e-03,
          8.6658e-03,  2.1755e-03, -1.2784e-02, -1.2027e-02,  1.4118e-02,
         -1.1834e-02, -1.0385e-02,  1.3922e-02,  1.2504e-02, -1.7128e-03],
        [-1.3055e-02, -7.5641e-03, -5.0677e-03, -1.2371e-02, -1.2903e-02,
         -1.2322e-02,  1.1078e-02, 

In [16]:
from model import ObjectDetectionModel as ObjModelFull
from model_compressed import ObjectDetectionModel as ObjModelCompressed

In [17]:
def count_parameters(model):
    """
    Conta il numero di parametri nel modello.

    Args:
    - model (nn.Module): Il modello PyTorch di cui contare i parametri.

    Returns:
    - int: Il numero totale di parametri nel modello.
    """
    return sum(p.numel() for p in model.parameters())

In [18]:
count_parameters(ObjModelFull())

134690729

In [19]:
count_parameters(ObjModelCompressed())

9272562